version: '3.8'

services:
  backend:
    build: 
      context: ./TR-Backend
      dockerfile: Dockerfile
    container_name: hockeyeco_backend
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ./TR-Backend/.env
    networks:
      - hockeyeco_network

  frontend:
    build: 
      context: ./TR-Frontend
      dockerfile: Dockerfile
    container_name: hockeyeco_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hockeyeco_network

networks:
  hockeyeco_network:
    driver: bridge